name: Update README with Pinned Repos

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute.
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          repository: Aditya-Nagariya/Aditya-Nagariya
          ssh-strict: true
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          fetch-tags: false
          lfs: false
          submodules: false
          set-safe-directory: true

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Update README
        run: node update-readme.js
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with latest pinned repositories"
          git push
